config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :plays
  root 'plays#index'

end

app/models/play.rb
class Play < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
	before_action :find_play, only: [:show, :edit, :update, :destroy]
	def index
		@plays = Play.all.order("created_at DESC")
	end

	def show

	end

	def new
		@play = current_user.play.build

	def create
		@play = current_user.play.build(play_params)

		if @play.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @play.update(play_params)
			redirect_to play_path(@play)
		else
			render 'edit'
		end
	end

	def destroy
		@play.destroy
		redirect_to root_path
	end
			

	private

	def play_params
		params.require(:play).permit(:title, :description, :director)
	end

	def find_play
		@play = Play.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Genmovies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Genmovies", root_path, class: "navbar-brand" %>
    </div>
   <ul class="nav navbar-nav navbar-right">
   	<% if user_signed_in? %>
   		<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
   	<% else %>
   	<li><%= link_to "Sign Up",new_user_registration_path %></li>
   	<li><%= link_to "Log In",new_user_session_path %></li>

   	<% end %>
   </ul>
   <ul class="nav navbar-nav">
   	<% if user_signed_in? %>
   		<li><%= link_to "Add Play", new_play_path %></li>
   	<% end %>
   </ul>
    </div>
    </nav>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<div class="container">
		<%= yield %>
	</div>



</body>
</html>

app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
  <%= f.input :title, label: "Movie Title" %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.button :submit %>
<% end %>

app/views/plays/edit.html.erb
<h1> Edit Genesis Movie </h1>
<%= render 'form' %>

app/views/plays/index.html.erb
<% @plays.each do |play| %>
<h2><%= link_to play.title, play_path(play) %></h2>
<% end %>

<%= link_to "Add Play", new_play_path %> 

app/views/plays/new.html.erb
<h1> New Genesis Movie </h1>
<%= render 'form' %>

app/views/plays/show.html.erb
<h2><%= @play.title %></h2>
<h3><%= @play.director %></h3>
<p><%= @play.description %></p>
<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_play_path(@play) %>
<%= link_to "Delete", play_path(@play), method: :delete, data: {confirm: "Are you Sure to Delete?"} %>